quarkus:
  http:
    port: 8084

mp:
  messaging:
    incoming:
      "bonus-events-in":
        connector: smallrye-kafka
        topic: player-bonus-updates
        commit-strategy: throttled
    outgoing:
      "login-events-out":
        connector: smallrye-kafka
        topic: player-login-events
        enable.idempotence: true
        acks: all
        retries: 5
        max.in.flight.requests.per.connection: 5
